// noinspection SpellCheckingInspection
/**
 * Maps the ship name (lower case for the file name) to the ship id
 */
export const shipNames = new Map<string, { id: number; master: string }>([
    ["agamemnon", { id: 694, master: "" }],
    ["basiccutter", { id: 413, master: "cutter" }],
    ["basiclynx", { id: 275, master: "lynx" }],
    ["bellepoule", { id: 264, master: "" }],
    ["bellona", { id: 265, master: "" }],
    ["bellona74", { id: 359, master: "" }],
    ["brig", { id: 266, master: "" }],
    ["brigmr", { id: 267, master: "" }],
    ["bucentaure", { id: 268, master: "" }],
    ["cerberus", { id: 269, master: "" }],
    ["christian", { id: 1664, master: "" }],
    ["christian2", { id: 2487, master: "" }],
    ["constitution", { id: 270, master: "" }],
    ["constitution2", { id: 1674, master: "" }],
    ["cutter", { id: 271, master: "" }],
    ["de_ruyter", { id: 2318, master: "" }],
    ["diana", { id: 1665, master: "" }],
    ["endymion", { id: 768, master: "" }],
    ["essex", { id: 272, master: "" }],
    ["frigate", { id: 273, master: "" }],
    ["grosventre", { id: 396, master: "" }],
    ["grosventrepirate", { id: 1561, master: "" }],
    ["gunboat", { id: 695, master: "" }],
    ["hamburg", { id: 970, master: "" }],
    ["hercules", { id: 1675, master: "" }],
    ["hermione", { id: 592, master: "" }],
    ["implacable", { id: 2235, master: "" }],
    ["indefatiable", { id: 787, master: "" }],
    ["indiaman", { id: 425, master: "" }],
    ["ingermanland", { id: 395, master: "" }],
    ["leopard", { id: 2078, master: "" }],
    ["lhermione", { id: 986, master: "" }],
    ["lynx", { id: 274, master: "" }],
    ["mercury", { id: 276, master: "" }],
    ["navybrig", { id: 277, master: "" }],
    ["niagara", { id: 278, master: "" }],
    ["ocean", { id: 650, master: "" }],
    ["pandora", { id: 1020, master: "" }],
    ["pavel", { id: 279, master: "" }],
    ["pickle", { id: 280, master: "" }],
    ["piratefrigate", { id: 281, master: "" }],
    ["princedeneufchatel", { id: 1125, master: "" }],
    ["privateer", { id: 282, master: "" }],
    ["rattlesnake", { id: 283, master: "" }],
    ["rattlesnakeheavy", { id: 284, master: "" }],
    ["renommee", { id: 285, master: "" }],
    ["requin", { id: 1676, master: "" }],
    ["rotterdam", { id: 2895, master: "" }],
    ["santa_ana", { id: 2892, master: "" }],
    ["santisima", { id: 286, master: "" }],
    ["snow", { id: 287, master: "" }],
    ["surprise", { id: 288, master: "" }],
    ["temeraire", { id: 2229, master: "" }],
    ["trader brig", { id: 289, master: "brig" }],
    ["trader cutter", { id: 290, master: "cutter" }],
    ["trader lynx", { id: 291, master: "lynx" }],
    ["trader snow", { id: 292, master: "snow" }],
    ["trincomalee", { id: 293, master: "" }],
    ["victory", { id: 294, master: "" }],
    ["victory1765", { id: 2350, master: "" }],
    ["wasa", { id: 1021, master: "" }],
    ["wasa_prototype", { id: 1938, master: "" }],
    ["yacht", { id: 295, master: "" }],
    ["yachtsilver", { id: 393, master: "" }],
])

export const getShipId = (baseFileName: string): number => shipNames.get(baseFileName)?.id ?? 0

export const getShipMaster = (baseFileName: string): string => shipNames.get(baseFileName)?.master ?? ""
